[package]
name = "yamaha-rcp-to-osc"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.38", features = ["derive"] }
rosc = "0.11.4"
tokio = { version = "1.45.0", features = ["full"] }
