name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            artifact_name: yamaha-rcp-to-osc
            asset_name: yamaha-rcp-to-osc-macos
          - os: windows-latest
            artifact_name: yamaha-rcp-to-osc.exe
            asset_name: yamaha-rcp-to-osc-windows.exe

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.os == 'windows-latest' && 'x86_64-pc-windows-msvc' || 'x86_64-apple-darwin' }}

      - name: Build
        run: cargo build --release

      - name: Prepare asset
        shell: bash
        run: |
          cd target/release
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            7z a ../../${{ matrix.asset_name }}.zip ${{ matrix.artifact_name }}
          else
            tar -czf ../../${{ matrix.asset_name }}.tar.gz ${{ matrix.artifact_name }}
          fi

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ matrix.asset_name }}.${{ matrix.os == 'windows-latest' && 'zip' || 'tar.gz' }}